export const NEWS_SOURCES = [
  {
    name: 'BBC',
    domains: ['bbc.com', 'bbc.co.uk'],
    tier: 1,
    weight: 3,
  },
  {
    name: 'New York Times',
    domains: ['nytimes.com'],
    tier: 3,
    weight: 1,
  },
  {
    name: 'CNN',
    domains: ['cnn.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'The Guardian',
    domains: ['theguardian.com'],
    tier: 3,
    weight: 1,
  },
  {
    name: 'USA Today',
    domains: ['usatoday.com'],
    tier: 3,
    weight: 1,
  },
  {
    name: 'CNBC',
    domains: ['cnbc.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'Al Jazeera',
    domains: ['aljazeera.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'Associated Press',
    domains: ['apnews.com'],
    tier: 1,
    weight: 3,
  },
  {
    name: 'Wall Street Journal',
    domains: ['wsj.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'Reuters',
    domains: ['reuters.com'],
    tier: 1,
    weight: 3,
  },
  {
    name: 'Washington Post',
    domains: ['washingtonpost.com'],
    tier: 3,
    weight: 1,
  },
  {
    name: 'Forbes',
    domains: ['forbes.com'],
    tier: 3,
    weight: 1,
  },
  {
    name: 'NBC News',
    domains: ['nbcnews.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'CBS News',
    domains: ['cbsnews.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'The Independent',
    domains: ['independent.co.uk'],
    tier: 3,
    weight: 1,
  },
  {
    name: 'NPR',
    domains: ['npr.org'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'CBC',
    domains: ['cbc.ca'],
    tier: 1,
    weight: 3,
  },
  {
    name: 'Sky News',
    domains: ['news.sky.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'ABC News',
    domains: ['abcnews.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'The Hill',
    domains: ['thehill.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'Business Insider',
    domains: ['businessinsider.com'],
    tier: 3,
    weight: 1,
  },
  {
    name: 'Financial Times',
    domains: ['ft.com'],
    tier: 1,
    weight: 3,
  },
  {
    name: 'Bloomberg',
    domains: ['bloomberg.com'],
    tier: 3,
    weight: 1,
  },
  {
    name: 'Politico',
    domains: ['politico.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'Axios',
    domains: ['axios.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'The Economist',
    domains: ['economist.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'TIME',
    domains: ['time.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'Los Angeles Times',
    domains: ['latimes.com'],
    tier: 2,
    weight: 2,
  },
  {
    name: 'ProPublica',
    domains: ['propublica.org'],
    tier: 1,
    weight: 3,
  },
  {
    name: 'PBS News',
    domains: ['pbs.org'],
    tier: 2,
    weight: 2,
  },
]